stages:
  - build
  - test
  - publish
  - deploy

build_job:
  stage: build
  script:
    - dotnet sonarscanner begin
      /k:crmsdk
      /d:sonar.host.url=http://sonar.drivecentric.com:9000
      /d:sonar.login=%SONAR_API_KEY%
      /d:sonar.gitlab.project_id=%CI_PROJECT_PATH%
      /d:sonar.gitlab.commit_sha=%CI_COMMIT_SHA%
      /d:sonar.gitlab.ref_name=%CI_COMMIT_REF_NAME%
      /d:sonar.gitlab.failure_notification_mode=commit-status
      /d:sonar.gitlab.json_mode=CODECLIMATE
      /d:sonar.gitlab.all_issues=false
      /d:sonar.analysis.mode=publish
      /d:sonar.cs.opencover.reportsPaths=%CD%/testResults/coverage.opencover.xml
      /d:sonar.branch.name=%CI_COMMIT_REF_NAME%
    - dotnet build
  artifacts:
    paths:
      - "*/bin"
      - "*/obj"
      - ".sonarqube"
      - codeclimate.json

publish_job:
  stage: publish
  dependencies:
    - build_job
  script:
    - dotnet publish -c release
  artifacts:
    paths:
      - "Services/DriveCentric.TaskService/bin/Release/netcoreapp2.1/publish"

deploy_job:
  stage: deploy
  dependencies:
    - publish_job
  script:
    - C:\Tools\Octo\Octo.exe pack -id Atlas-TaskService --version %CI_PIPELINE_IID%-%CI_COMMIT_REF_NAME% --basePath Services\DriveCentric.TaskService\bin\Release\netcoreapp2.1\publish
    - C:\Tools\Octo\Octo.exe push --package .//Atlas-TaskService.%CI_PIPELINE_IID%-%CI_COMMIT_REF_NAME%.nupkg --replace-existing --server https://deploy2.drivecentric.com --apiKey %OCTOPUS_API_KEY%