stages:
  - build
  - test
  - publish
  - deploy

build_job:
  stage: build
  script:
    - dotnet build
  artifacts:
    paths:
      - "*/bin"
      - "*/obj"

test_job:
  stage: test
  script:
    - dotnet test .\RestApi.Tests\DriveCentric.RestApi.Tests.csproj
    - dotnet test .\ServiceLayer.CoreTests\DriveCentric.ServiceLayer.CoreTests.csproj
    - dotnet test .\Utilities.CoreTests\DriveCentric.Utilities.CoreTests.csproj
    - dotnet test .\Business\BusinessLogic.CoreTests\DriveCentric.BusinessLogic.CoreTests.csproj
    - dotnet test .\Data\SqlORM.CoreTests\DriveCentric.Data.SqlORM.CoreTests.csproj

publish_job:
  stage: publish
  dependencies:
    - build_job
  script:
    - dotnet publish -c release
  artifacts:
    paths:
      - "Services/DriveCentric.TaskService/bin/Release/netcoreapp2.1/publish"

deploy_job:
  stage: deploy
  dependencies:
    - publish_job
  script:
    - C:\Tools\Octo\Octo.exe pack -id Atlas-TaskService --version %CI_PIPELINE_IID%-%CI_COMMIT_REF_NAME% --basePath Services\DriveCentric.TaskService\bin\Release\netcoreapp2.1\publish
    - C:\Tools\Octo\Octo.exe push --package .//Atlas-TaskService.%CI_PIPELINE_IID%-%CI_COMMIT_REF_NAME%.nupkg --replace-existing --server https://deploy2.drivecentric.com --apiKey %OCTOPUS_API_KEY%